# Start from the official Go image
FROM golang:1.23.2-alpine
# Set the Current Working Directory inside the container
WORKDIR /app
COPY ./app .
ENV GIN_MODE=release
RUN go mod download
RUN go build -o ./cmd/web/main ./cmd/web/main.go 
EXPOSE 8080
CMD ["go", "run", "./cmd/web/main.go"]